








upstream auth_service {

    server 127.0.0.1:9005;

}


































upstream home_service {

    server 127.0.0.1:9001;

}














upstream payment_service {

    server 127.0.0.1:9002;

}








server {
    listen 8080;
    server_name localhost;










    location /api/auth/ {
        proxy_pass http://auth_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


































    location /api/home/ {
        proxy_pass http://home_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }














    location /api/payment/ {
        proxy_pass http://payment_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }







}